### ISSUE TITLE
Possible optimization via compression

### ISSUE THREAD

**Issue by bradbaris** [sgnl/sundaysale.club#6]
I noticed that since you're storing the brochures on mongo, maybe you could compress them (either on-the-fly when served, or before being stored in db). I think it could help mobile users on location by saving bandwidth on their data plans when they visit the [sundaysale.club](https://sundaysale.club/). Not sure if Longs offers in-store wifi, but hopefully they do.

The March brochure clocks in at 66MB.  Optimized via a [simple bash script](https://github.com/CristianCantoro/shrinkpdf) (using built-in `gs`) and a couple minutes, it can crunch down to 6MB. Maybe ~80% of a PDF's weight is in the bitmap images after all.

🤖

**Comment by sgnl** [comment]
Im not storing them in mongo. Im just storing the urls to the pdfs

**Comment by sgnl** [comment]
Im wondering if it would be better to slice the pages and convert them to a better image format

**Comment by sgnl** [comment]
Closing. Moving this to the sgnl/sundaysale.club-cron repo
